apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aws-node-binding
subjects:
- kind: User
  name: "arn:aws:iam::000000000000:root"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: aws-node
  apiGroup: rbac.authorization.k8s.io
