# kubectl create secret docker-registry ecr-registry-secret --docker-server=000000000000.dkr.ecr.ap-northeast-2.amazonaws.com --docker-username=AWS --docker-password=$(aws ecr get-login-password --region ap-northeast-2) --dry-run=server -o yaml
apiVersion: v1
kind: Secret
metadata:
  name: ecr-registry-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: 
